.TH "src/Objects/EnemyType.h" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Objects/EnemyType.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyType\fP"
.br
.RI "The base class for different types of enemies in the game\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
