.TH "src/Objects/EnemyTypeC.cpp" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Objects/EnemyTypeC.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'EnemyTypeC\&.h'\fP
.br
\fC#include 'enemies\&.h'\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
