.TH "src/Objects/EnemyTypeD.h" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Objects/EnemyTypeD.h
.SH SYNOPSIS
.br
.PP
\fC#include 'EnemyType\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyTypeD\fP"
.br
.RI "\fBEnemyTypeD\&.h\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
