.TH "Tile" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTile\fP (const sf::Vector2f &position, const sf::Color &color, int tileSize)"
.br
.ti -1c
.RI "sf::RectangleShape & \fBgetShape\fP ()"
.br
.ti -1c
.RI "sf::Vector2f & \fBgetPosition\fP ()"
.br
.ti -1c
.RI "const sf::Color & \fBgetColor\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tile::Tile (const sf::Vector2f & position, const sf::Color & color, int tileSize)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const sf::Color & Tile::getColor () const\fC [inline]\fP"

.SS "sf::Vector2f & Tile::getPosition ()\fC [inline]\fP"

.SS "sf::RectangleShape & Tile::getShape ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
