.TH "src/tiles.cpp" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tiles.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTile\fP & \fBfindClosestTile\fP (std::vector< \fBTile\fP > &\fBtiles\fP, const sf::Vector2f &position)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBTile\fP & findClosestTile (std::vector< \fBTile\fP > & tiles, const sf::Vector2f & position)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
