.TH "TowerType" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TowerType \- \fBTower\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tower\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTowerType\fP (double radius, int damage, double attack_range, double attack_speed, const sf::Color &color, int cost)"
.br
.RI "Constructs a \fBTowerType\fP object with the specified parameters\&. "
.ti -1c
.RI "double \fBgetRadius\fP () const"
.br
.RI "Gets the radius of the tower\&. "
.ti -1c
.RI "int \fBgetDamage\fP () const"
.br
.RI "Gets the damage inflicted by the tower\&. "
.ti -1c
.RI "double \fBgetAttackRange\fP () const"
.br
.RI "Gets the attack range of the tower\&. "
.ti -1c
.RI "double \fBgetAttackSpeed\fP () const"
.br
.RI "Gets the attack speed of the tower\&. "
.ti -1c
.RI "const sf::Color & \fBgetColor\fP () const"
.br
.RI "Gets the color of the tower\&. "
.ti -1c
.RI "int \fBgetCost\fP () const"
.br
.RI "Gets the cost of the tower\&. "
.ti -1c
.RI "\fB~TowerType\fP ()"
.br
.RI "Destructor for the \fBTowerType\fP object\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTower\fP class\&. 

Represents a type of tower in the tower defense game\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TowerType::TowerType (double radius, int damage, double attack_range, double attack_speed, const sf::Color & color, int cost)"

.PP
Constructs a \fBTowerType\fP object with the specified parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIradius\fP The radius of the tower\&. 
.br
\fIdamage\fP The damage inflicted by the tower\&. 
.br
\fIattack_range\fP The attack range of the tower\&. 
.br
\fIattack_speed\fP The attack speed of the tower\&. 
.br
\fIcolor\fP The color of the tower\&. 
.br
\fIcost\fP The cost of the tower\&. 
.RE
.PP

.SS "TowerType::~TowerType ()\fC [inline]\fP"

.PP
Destructor for the \fBTowerType\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "double TowerType::getAttackRange () const"

.PP
Gets the attack range of the tower\&. 
.PP
\fBReturns\fP
.RS 4
The attack range of the tower\&. 
.RE
.PP

.SS "double TowerType::getAttackSpeed () const"

.PP
Gets the attack speed of the tower\&. 
.PP
\fBReturns\fP
.RS 4
The attack speed of the tower\&. 
.RE
.PP

.SS "const sf::Color & TowerType::getColor () const"

.PP
Gets the color of the tower\&. 
.PP
\fBReturns\fP
.RS 4
The color of the tower\&. 
.RE
.PP

.SS "int TowerType::getCost () const\fC [inline]\fP"

.PP
Gets the cost of the tower\&. 
.PP
\fBReturns\fP
.RS 4
The cost of the tower\&. 
.RE
.PP

.SS "int TowerType::getDamage () const"

.PP
Gets the damage inflicted by the tower\&. 
.PP
\fBReturns\fP
.RS 4
The damage inflicted by the tower\&. 
.RE
.PP

.SS "double TowerType::getRadius () const"

.PP
Gets the radius of the tower\&. 
.PP
\fBReturns\fP
.RS 4
The radius of the tower\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
