.TH "src/Objects/tower.h" 3 "Tower Defence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Objects/tower.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'enemies\&.h'\fP
.br
\fC#include '\&.\&./gameEngine\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTowerType\fP"
.br
.RI "\fBTower\fP class\&. "
.ti -1c
.RI "class \fBTower\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tower Defence from the source code\&.
